function Subj01Test11 = importVICONdataFullbody(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SUBJ01TEST11 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  SUBJ01TEST11 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Subj01Test11 = importfile("E:\Google Drive\[2] Project Folder\2021 IMU\Matlab\2021_0129 IMU walk full body\Vicon_Data\Subj01_Test11.csv", [6, 26330]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Feb-2021 13:27:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 119);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "Subj01LFHD", "VarName4", "VarName5", "Subj01RFHD", "VarName7", "VarName8", "Subj01LBHD", "VarName10", "VarName11", "Subj01RBHD", "VarName13", "VarName14", "Subj01C7", "VarName16", "VarName17", "Subj01T10", "VarName19", "VarName20", "Subj01CLAV", "VarName22", "VarName23", "Subj01STRN", "VarName25", "VarName26", "Subj01RBAK", "VarName28", "VarName29", "Subj01LSHO", "VarName31", "VarName32", "Subj01LUPA", "VarName34", "VarName35", "Subj01LELB", "VarName37", "VarName38", "Subj01LFRM", "VarName40", "VarName41", "Subj01LWRA", "VarName43", "VarName44", "Subj01LWRB", "VarName46", "VarName47", "Subj01LFIN", "VarName49", "VarName50", "Subj01RSHO", "VarName52", "VarName53", "Subj01RUPA", "VarName55", "VarName56", "Subj01RELB", "VarName58", "VarName59", "Subj01RFRM", "VarName61", "VarName62", "Subj01RWRA", "VarName64", "VarName65", "Subj01RWRB", "VarName67", "VarName68", "Subj01RFIN", "VarName70", "VarName71", "Subj01LASI", "VarName73", "VarName74", "Subj01RASI", "VarName76", "VarName77", "Subj01LPSI", "VarName79", "VarName80", "Subj01RPSI", "VarName82", "VarName83", "Subj01LTHI", "VarName85", "VarName86", "Subj01LKNE", "VarName88", "VarName89", "Subj01LTIB", "VarName91", "VarName92", "Subj01LANK", "VarName94", "VarName95", "Subj01LHEE", "VarName97", "VarName98", "Subj01LTOE", "VarName100", "VarName101", "Subj01RTHI", "VarName103", "VarName104", "Subj01RKNE", "VarName106", "VarName107", "Subj01RTIB", "VarName109", "VarName110", "Subj01RANK", "VarName112", "VarName113", "Subj01RHEE", "VarName115", "VarName116", "Subj01RTOE", "VarName118", "VarName119"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Subj01Test11 = readtable(filename, opts);

%% Convert to output type
Subj01Test11 = table2array(Subj01Test11);
end